### ISSUE TITLE
Actions won't get logged if using redux-thunk

### ISSUE THREAD

**Issue by hannupekka** [ngokevin/redux-raven-middleware#15]
Since at this point (https://github.com/ngokevin/redux-raven-middleware/blob/master/index.es6#L21) action is dispatch function returned from redux-thunk style action creator.

**Comment by captbaritone** [comment]
Moving the Raven middleware after the thunk middleware solved this problem for me.

**Comment by burtyish** [comment]
> Moving the Raven middleware after the thunk middleware solved this problem for me.

...which is exactly the opposite of what the folks at Sentry recommended in [this blog post](https://blog.sentry.io/2016/08/24/redux-middleware-error-logging.html).
![rich_error_reports_with_redux_middleware](https://cloud.githubusercontent.com/assets/4200728/22625256/d530cbca-eb99-11e6-8cdf-235392f87cbf.png)

**Comment by captbaritone** [comment]
Yeah, I found that confusing as well. Does anyone know why they recommend putting it before the Thunk middleware? Perhaps to ensure that any errors encountered within the thunk middleware/wrapper function get caught?
