### ISSUE TITLE
Update redux-raven-middleware on NPM

### ISSUE THREAD

**Issue by adrianha** [ngokevin/redux-raven-middleware#16]
Hi @ngokevin,
it looks like this library is not updated on NPM since there is no `options` parameter to pass transformer (action or state).

**Comment by mull** [comment]
@ngokevin project abandoned?

**Comment by ngokevin** [comment]
published

**Comment by ngokevin** [comment]
Yeah, if anyone wants to maintain this library, they can take control.

**Comment by mull** [comment]
Sorry to hear that. Unfortunately I found out immediately that we cannot use this middleware as our state grows too big for Sentry to accept the payload for nearly all of our pages. :/

**Comment by idris** [comment]
@ngokevin I'd be happy to take over maintenance of the library.  If you want to add `idris` as an admin/owner on the npm package, I can take over merging PRs and pushing updates.

**Comment by captbaritone** [comment]
FWIW, I have an actively maintained middleware that solves the same problem. Maybe we could merge projects?

https://github.com/captbaritone/raven-for-redux

**Comment by ngokevin** [comment]
I can add @idris as an owner and maybe later transfer it over. Thanks!

**Comment by ngokevin** [comment]
I can also link to raven for redux
