### ISSUE TITLE
Does this lib supercede direct raven usage

### ISSUE THREAD

**Issue by rt2zz** [ngokevin/redux-raven-middleware#20]
i.e. should I also set up raven per normal, or does redux-raven-middleware give me global error reporting + redux integration?

**Comment by karlfloersch** [comment]
@rt2zz I too was wondering this. It seems, from reading the source, that you are not required to install Raven in the normal method when using this library. See this:

https://github.com/ngokevin/redux-raven-middleware/blob/master/index.es6#L16

**Comment by captbaritone** [comment]
Could be fixed with a different approach, proposed here: https://github.com/ngokevin/redux-raven-middleware/issues/23

**Comment by captbaritone** [comment]
If you wish/need to use a pre-existing instance of `Raven` (such as if you are including Raven from Sentry's CDN, or just via its own `<script>` tag, I've published an alternative library that allows you to pass in your own `Raven`: https://github.com/captbaritone/raven-for-redux
