### ISSUE TITLE
how can you send actions/state for non-redux errors?

### ISSUE THREAD

**Issue by faceyspacey** [ngokevin/redux-raven-middleware#21]
Can this capture errors that *don't* happen in redux action creators and reducers? 

In other words, how can we send redux state along with **every** error reported by sentry?

**Comment by joshwcomeau** [comment]
I suspect that it would be much harder to build that kind of tool; the nice thing about redux is it imposes a structure, a "pass-through" point. Trying to capture application-wide errors would likely require monkeypatching raven.js, or it would be very application-specific implementation.

**Comment by faceyspacey** [comment]
@joshwcomeau actually you can probably do it with callbacks like `dataCallback` provided as config: https://docs.sentry.io/clients/javascript/config/

just have your store in scope and call `getState` on it ahead of time for the state. for actions, you basically just build a simple middleware replicating what `mock-redux-store` does in its `getActions` method, and collect that before any error reported as well.

**Comment by joshwcomeau** [comment]
Oh, cool. Thanks for pointing that out @faceyspacey!

**Comment by captbaritone** [comment]
[raven-for-redux](https://github.com/captbaritone/raven-for-redux) uses `dataCallback` to attach the last action and the current state as Raven context for all errors, not just reducer errors.
