### ISSUE TITLE
413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by icd2k3** [ngokevin/redux-raven-middleware#25]
Any ideas why I might be hitting this? My source maps are well under the limit (largest is 1.5mb). My sourcemaps are hosted on sentry and not uploaded to aws.

The request looks normal to me:
![sentry](https://www.dropbox.com/s/1bjk829er5xwt00/Screenshot%202017-03-24%2010.19.40.png?raw=1)

redux-raven-middleware@1.2.0
sentry_version:7
sentry_client:raven-js/3.12.0

**Comment by icd2k3** [comment]
Adding `maxBreadcrumbs: 5` to the config fixes the issue - not ideal, but good enough for now!

**Comment by Sedighian** [comment]
For me the state was huge so I recommend actually using `stateTransformer ` over limiting your breadcrumbs. https://github.com/captbaritone/raven-for-redux#statetransformer-function
