### ISSUE TITLE
Additional Data section of Sentry doesn't show current state and the action 

### ISSUE THREAD

**Issue by maksad** [ngokevin/redux-raven-middleware#3]
The [source code](https://github.com/ngokevin/redux-raven-middleware/blob/master/index.js#L47-#L50) shows that if there is an error then the Raven extra fields should have `action` and current state - `store.getState()`. 
However, when intentionally raising an error in my code to catch in Sentry:

```
  componentWillMount() {
    nonExistingFunctionCalled();
  }
```

Sentry states only about the `session:duration` and no any information can be found about `action` and `state`.

Here is a screenshot:

![screen shot 2015-10-02 at 09 19 54](https://cloud.githubusercontent.com/assets/4527650/10240670/ad809622-68e7-11e5-9d40-812c77cfefc3.png)

**Comment by Hyra** [comment]
Same here. Not sure if it's related, but i also get the message 'Error: Raven has not been configured.' in the console.

**Comment by ngokevin** [comment]
@maksad the middleware only handles errors raised on actions, not component-level code. Redux middleware wraps every action where we have access to getState, Redux middleware doesn't touch component-level code. Let me know if that makes sense.

@hyra hmm, are you initializing the middleware with your Sentry DSN? I wonder what's happening there.

**Comment by Hyra** [comment]
@ngokevin: yeah, i just added the middleware like so:

```
const createStoreWithMiddleware = applyMiddleware(
  thunkMiddleware,
  loggerMiddleware,
  RavenMiddleware('https://******@app.getsentry.com/abcdefg')
)(createStore);
```

Could it be because I'm running a local webserver on 127.0.0.1 ..

Want me to create a separate ticket for it?

**Comment by ngokevin** [comment]
@hyra yeah you can file another one, i'll check it out. Put all the logs/details you have. thanks!

**Comment by Hyra** [comment]
Done at #4 ! Cheers!

**Comment by ngokevin** [comment]
@maksad i'm going to close this. Try triggering the error in an action, or let me know if you have any ideas on how to feed the Redux state into Raven at the component-level.

**Comment by maksad** [comment]
Thanks @ngokevin 
Yes you are right. I triggered an error in Reducer and it captured the issue:

![screen shot 2015-10-02 at 10 44 05](https://cloud.githubusercontent.com/assets/4527650/10241555/a33cc1b2-68f2-11e5-85cd-3745f9bb9aaa.png)

I will write when there will be a proper solution for feeding the Redux state into Raven at the component-level.

**Comment by maksad** [comment]
@ngokevin 
This code lets you capture an error with the state in the component-level:

```
RavenMiddleware(
  'https://**************************************@app.getsentry.com/xxxxx',
  {
    collectWindowErrors: true,
    dataCallback: (data) => {
      const store = require('path-to-the-stores/Store');
      if (!(data.extra && data.extra.state)) {
        try {
          data.extra.state = store.getState();
        } catch (expt) {
          console.log(expt);
        }
      }
      return data;
    }
  }
)];
```

**Comment by ngokevin** [comment]
Nice, glad that can be done. Might be worth documenting
