### ISSUE TITLE
Configuration to add environment to Sentry errors

### ISSUE THREAD

**Issue by cdimitroulas** [ngokevin/redux-raven-middleware#32]
How do I go about adding the environment (development/production) to the Sentry error with this library?

I tried doing this but it doesn't seem to work:
```
RavenMiddleware(process.env.SENTRY_URL, {
  environment: process.env.NODE_ENV
})
```

**Comment by captbaritone** [comment]
I would expect that to work. Are you sure `process.env.NODE_ENV` contains what you think it does?

**Comment by cdimitroulas** [comment]
Yes, I've just gone back and double-checked it and `process.env.NODE_ENV` is either `development` or `production` as expected.
I am not seeing the usual `environment` tag on Sentry that I see on other applications where I have Sentry set up such as in the image below
![image](https://cloud.githubusercontent.com/assets/20640274/26575633/ee918bb2-451d-11e7-9357-227ed81d54b1.png)

**Comment by captbaritone** [comment]
Is it possible that `Raven` is already setup in your environment? It should be pretty simple to set a break point (`debugger`) before you call `RavenMiddleware` and then step though the function. The real question would be, what is `cfg` at this line: https://github.com/ngokevin/redux-raven-middleware/blob/master/index.js#L43 (or does that line even get called)?

**Comment by cdimitroulas** [comment]
I do have `raven-js` also set up so that I can manually capture errors such as inside a `catch` statement`.

I now see that you are using raven-js internally so that is what is causing the issue. Am I able to use Raven for capturing caught exceptions manually using this library? Or should I just add my config when I set up `raven-js` and not try to do it when I set up the `RavenMiddleware`?

**Comment by captbaritone** [comment]
You might want to check out [raven-for-redux](https://github.com/captbaritone/raven-for-redux) it's a similar library except that it allows you to pass your own `Raven` object, which makes it easier to have access to the `Raven` object for other purposes, such as manual captures.

It also has a few other differences which you can read about in the README.

Disclosure: I maintain `raven-for-redux`.
