### ISSUE TITLE
Is this middleware beneficial?

### ISSUE THREAD

**Issue by ghost** [ngokevin/redux-raven-middleware#5]
I'm curious, what are the benefits of using this middleware when Raven is designed to capture exceptions at the `window` scope out of the box (assuming the following known issue is fixed): https://github.com/getsentry/raven-js/issues/424

**Comment by ngokevin** [comment]
It also passes the Redux store to Sentry. Some issues with Sentry not being able to handle large messages though.

**Comment by ghost** [comment]
What you mentioned. Passing Redux store to Sentry. I could see that being useful in the recreation of errors assuming state can be properly reconstructed from the object passed. The risk involved is that it's more likely sensitive data, which could be temporarily stored in app state, such as Personally Identifiable Information or passwords, could also be passed inadvertently if that info is not redacted somehow prior to transmission.
