### ISSUE TITLE
Publish new version (0.4.0?)

### ISSUE THREAD

**Issue by benvinegar** [ngokevin/redux-raven-middleware#9]
Hey there,

It would be nice if you could cut a new version of redux-raven-middleware that represents the current state of the repo:
- breadcrumb collection
- latest version of Raven.js (which introduces breadcrumbs, POST requests so more data can be sent, etc)

Right now the [latest version on npm](https://www.npmjs.com/package/redux-raven-middleware) is 0.3.0, which is 11 months old.

If you need a hand maintaining this library, I'd be glad to come on as a contributor (I maintain [raven-js](/getsentry/raven-js) on behalf of Sentry).

**Comment by ngokevin** [comment]
Hi, thanks for the help! Added you as a collaborator.

If you think there's a lot of work to be done on this project, we can transfer this project to you. You'd definitely be a better maintainer since you maintain raven :)

**Comment by ngokevin** [comment]
I bumped to 1.0.0

**Comment by benvinegar** [comment]
> If you think there's a lot of work to be done on this project, we can transfer this project to you. You'd definitely be a better maintainer since you maintain raven :)

I think for the meantime we're cool as it is. I am thinking about refactoring all of the raven-js plugins into some kind of big multi-project [Lerna](/lerna/lerna) monorepo – if we get to that point I'd explore pulling this behavior into an official plugin.
